import { useQuery } from '@tanstack/react-query'
import { Plus, Calendar, MapPin } from 'lucide-react'
import { albumsApi } from '../services/api'

export function AlbumsPage() {
  const { data: albumsData, isLoading } = useQuery({
    queryKey: ['albums'],
    queryFn: albumsApi.getAlbums
  })

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-gray-900">Travel Albums</h1>
          <p className="text-gray-600 mt-2">
            Organize your photos into beautiful albums
          </p>
        </div>
        <button className="btn-primary">
          <Plus size={18} className="mr-2" />
          Create Album
        </button>
      </div>

      {isLoading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {Array.from({ length: 6 }).map((_, i) => (
            <div key={i} className="card p-6">
              <div className="h-48 bg-gray-200 rounded-lg animate-pulse mb-4"></div>
              <div className="h-4 bg-gray-200 rounded animate-pulse mb-2"></div>
              <div className="h-3 bg-gray-200 rounded animate-pulse w-3/4"></div>
            </div>
          ))}
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {albumsData?.data?.map((album: any) => (
            <div key={album.id} className="card overflow-hidden hover:shadow-lg transition-shadow">
              <div className="h-48 bg-gray-100 flex items-center justify-center">
                {album.coverPhoto ? (
                  <img
                    src={album.coverPhoto}
                    alt={album.title}
                    className="w-full h-full object-cover"
                  />
                ) : (
                  <Calendar className="text-gray-400" size={48} />
                )}
              </div>
              <div className="p-4">
                <h3 className="font-semibold text-lg mb-2">{album.title}</h3>
                {album.description && (
                  <p className="text-gray-600 text-sm mb-3 line-clamp-2">
                    {album.description}
                  </p>
                )}
                <div className="flex items-center justify-between text-sm text-gray-500">
                  <span>{album._count?.albumPhotos || 0} photos</span>
                  {album.isAutoGenerated && (
                    <span className="bg-blue-100 text-blue-700 px-2 py-1 rounded text-xs">
                      Auto-generated
                    </span>
                  )}
                </div>
              </div>
            </div>
          ))}
          
          {/* Create Album Card */}
          <div className="card border-dashed border-2 border-gray-300 hover:border-primary-400 transition-colors">
            <div className="h-48 flex items-center justify-center">
              <div className="text-center">
                <Plus className="mx-auto text-gray-400 mb-4" size={48} />
                <p className="text-gray-600 font-medium">Create New Album</p>
                <p className="text-gray-500 text-sm mt-1">
                  Organize your photos
                </p>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}